title = "âœ¨sitocttâœ¨"
#GitLab:baseURL = "https://sitoctt.octt.eu.org/"
#GitHub:baseURL = "http://http.sitoctt.octt.eu.org/"
#Offline:relativeURLs = true
#Offline:disableAliases = true
canonifyURLs = true
disablePathToLower = true
sectionPagesMenu = "main"
defaultContentLanguage = "it"
defaultContentLanguageInSubdir = true
theme = ["hugo-notice", "ananke"]

[pagination]
  pagerSize = 9

[permalinks]
  [permalinks.section]
    miscellanea = ":sections/"
  [permalinks.page]
    blog = ":section/:year-:month-:day-:slug/"
    note = ":section/:year-:month-:day-:slug/"
    miscellanea = ":sections/:slug/"

[languages]
  [languages.it]
    contentDir = "content/it"
    languageDirection = "ltr"
    languageName = "Italiano"
    weight = 1
    [languages.it.params]
      languageEmoji = "ğŸ‡®ğŸ‡¹âœ¨ï¸"
  [languages.en]
    contentDir = "content/en"
    languageDirection = "ltr"
    languageName = "English"
    weight = 2
    [languages.en.params]
      languageEmoji = "ğŸ‡¬ğŸ‡§"
  [languages.es]
    contentDir = "content/es"
    languageDirection = "ltr"
    languageName = "EspaÃ±ol"
    weight = 3
    [languages.es.params]
      languageEmoji = "ğŸ‡ªğŸ‡¸ï¸"
  [languages.fr]
    contentDir = "content/fr"
    languageDirection = "ltr"
    languageName = "FranÃ§ais"
    weight = 3
    [languages.fr.params]
      languageEmoji = "ğŸ‡«ğŸ‡·ï¸"

[markup]
  [markup.tableOfContents]
    endLevel = 4
  [markup.goldmark]
    [markup.goldmark.parser]
      [markup.goldmark.parser.attribute]
        block = true
        title = true
    [markup.goldmark.renderer]
      unsafe = true

[params]
  favicon = "/favicon.ico"
  author = "OctoSpacc"
  recent_posts_number = 5
  other_posts_number = 6
  toc = true
  show_reading_time = true
  canonicalUrlOverride = "https://sitoctt.octt.eu.org"
  #canonicalUrlOverride = "http://http.sitoctt.octt.eu.org"
  #custom_css = [ "Global.scss", "sitoctt.scss" ]

[outputFormats]
  [outputFormats.SearchIndex]
    mediaType = "text/javascript"
    baseName = "searchindex"
    isPlainText = true

[outputs]
  home = [ "HTML", "SearchIndex" ]

